version: 1
builder:
  configs:
    - platform: ios
      documentation_targets:
        - TowerSignalCore
        - TowerSignalLogs
        - TowerSignalTrace
        - TowerSignalRUM
        - TowerSignalSessionReplay
        - TowerSignalCrashReporting
        - TowerSignalWebViewTracking
        - TowerSignalFlags
        - TowerSignalProfiling
