## Workaround KSCrash static linking issue
# https://github.com/kstenerud/KSCrash/issues/713
use_modular_headers!
#

target 'Runner iOS' do
    platform :ios, '12.0'

    pod 'TowerSignalCore', :path => '..'
    pod 'TowerSignalLogs', :path => '..'
    pod 'TowerSignalTrace', :path => '..'
    pod 'TowerSignalRUM', :path => '..'
    pod 'TowerSignalCrashReporting', :path => '..'
    pod 'TowerSignalSessionReplay', :path => '..'
    pod 'TowerSignalWebViewTracking', :path => '..'

    target 'IntegrationScenarios' do
        pod 'TowerSignalInternal', :path => '..'
        pod 'TestUtilities', :path => '..'
    end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_ACTIVE_COMPILATION_CONDITIONS'] = '$(inherited) DD_SDK_ENABLE_EXPERIMENTAL_APIS DD_SDK_COMPILED_FOR_TESTING'
        end
    end
end
